# Generated by Django 4.2 on 2023-05-04 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('ROMANCE', 'ROM'), ('HORROR', 'HOR'), ('HISTORICAL', 'HIST'),
                                                    ('BATTLE', 'BAT'), ('COMEDY', 'COM'), ('DRAMA', 'DRA')])),
                ('popularity', models.FloatField(blank=True, null=True, validators=
                [django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9.99)])),
                ('seasons', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['popularity'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('role', models.CharField(choices=[('USER', 'U'), ('ADMIN', 'A'), ('VISITOR', 'V')])),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True, serialize=False, to='yummy.user')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('yummy.user', models.Model),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True, serialize=False, to='yummy.user')),
                ('admin_name', models.CharField(max_length=100, unique=True)),
            ],
            bases=('yummy.user',),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField()),
                ('id_anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('colour', models.CharField(choices=[('YELLOW', 'YEL'), ('BLUE', 'BL'), ('GREEN', 'GR')])),
                ('id_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
