# Generated by Django 4.2 on 2023-05-04 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0002_folder_id_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='video',
            field=models.FileField(null=True, upload_to='media/video_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
