# Generated by Django 4.2 on 2023-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0005_anime_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='favourites',
        ),
        migrations.AddField(
            model_name='folder',
            name='favourites',
            field=models.ManyToManyField(related_name='favorited_by', to='yummy.anime'),
        ),
    ]
