# Generated by Django 4.2 on 2023-05-09 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0007_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='video',
            field=models.FileField(max_length=250, null=True, upload_to='yummy/templates/media/video_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
