# Generated by Django 4.2 on 2023-05-09 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0008_alter_mediafile_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='video',
            field=models.FileField(max_length=250, null=True, upload_to='yummy_anime/yummy/templates/media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
