# Generated by Django 4.2 on 2023-05-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0012_achievement_user_alter_mediafile_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='media_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yummy.mediafile'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='timecode',
            field=models.TimeField(null=True),
        ),
    ]
