# Generated by Django 4.2 on 2023-05-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0013_alter_achievement_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='current_time',
            field=models.DurationField(default=0),
        ),
    ]
