# Generated by Django 4.2 on 2023-05-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0014_mediafile_current_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
