# Generated by Django 4.2 on 2023-05-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0015_delete_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='favourites',
        ),
    ]
