# Generated by Django 4.2 on 2023-05-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0016_remove_folder_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='current_time',
        ),
    ]
