# Generated by Django 4.2 on 2023-05-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
