# Generated by Django 4.2 on 2023-05-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0020_user_user_id_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_id_idx',
        ),
    ]
